In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.6'

In [4]:
# 0D array
zero_arr = np.array(10)
print(zero_arr)
print(type(zero_arr))
print(zero_arr.ndim,"Dimensions")
print(zero_arr.dtype)

10
<class 'numpy.ndarray'>
0 Dimensions
int64


In [5]:
# 1D array
one_arr = np.array([10,6,23])
print(one_arr)
print(type(one_arr))
print(one_arr.ndim,'end=dimensions')
print(one_arr.dtype)
print(one_arr.shape)

[10  6 23]
<class 'numpy.ndarray'>
1 end=dimensions
int64
(3,)


In [6]:
# 2D array
two_arr = np.array([[12,23,65,87],[11,22,98,76]])
print(two_arr)
print(type(two_arr))
print(two_arr.ndim,'end=dimensions')
print(two_arr.dtype)
print(two_arr.shape)

[[12 23 65 87]
 [11 22 98 76]]
<class 'numpy.ndarray'>
2 end=dimensions
int64
(2, 4)


In [7]:
# 3D array
three_arr = np.array([[[10,12,54,65],[65,75,9,16],[12,34,98,43]],
                     [[23,87,32,8],[12,62,31,71],[13,87,52,97]]])
print(three_arr)
print(type(three_arr))
print(three_arr.ndim,'end=dimensions')
print(three_arr.dtype)
print(three_arr.shape)


[[[10 12 54 65]
  [65 75  9 16]
  [12 34 98 43]]

 [[23 87 32  8]
  [12 62 31 71]
  [13 87 52 97]]]
<class 'numpy.ndarray'>
3 end=dimensions
int64
(2, 3, 4)


In [8]:
zero = np.zeros((4,4,2))
print(zero)
print(type(zero))
print(zero.ndim)
print(zero.dtype)


[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
<class 'numpy.ndarray'>
3
float64


In [11]:
one = np.ones((3,3,3))
print(one)
print(type(one))
print(one.ndim)
print(one.dtype)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
3
float64


In [12]:
mat = np.array(['2','surendra', 'mat'])
print(mat)
print(type(mat))
print(mat.dtype)

['2' 'surendra' 'mat']
<class 'numpy.ndarray'>
<U8


In [16]:
one_arr = np.array([10,65,34])
print(one_arr[2])
print(one_arr[0])
print(one_arr[-1])
print(one_arr[-2])

34
10
34
65


In [30]:
two_arr = np.array([[12,34,76,34],[12,98,65,234]])
print(two_arr)
print(two_arr[0])
print(two_arr[1])
print(two_arr[0][3])
print(two_arr[1][3])
print(two_arr[1][-1])
print(two_arr[-2][-2])
print(two_arr[1][1:3])

[[ 12  34  76  34]
 [ 12  98  65 234]]
[12 34 76 34]
[ 12  98  65 234]
34
234
234
76
[98 65]


In [40]:
three_arr = np.array([[[12,34,76,34],[12,98,65,234]],[[123,34,765,32],[15,71,91,62]]])
print(three_arr[1][0][0])
print(three_arr[0])
print(three_arr[0][1])
print(three_arr[0][0][::-1])

123
[[ 12  34  76  34]
 [ 12  98  65 234]]
[ 12  98  65 234]
[34 76 34 12]


In [55]:
a = np.array([1,2,3])
b = np.array([4,5,6])
add = np.add(a,b)
sub  = np.subtract(a,b)
mult = np.multiply(a,b)
div = np.divide(a,b)
print(a+b)
print(add)
print(sub)
print(mult)
print(div)
print(b//a)
print(np.floor_divide(b,a))
print(np.mod(a,b))
print(a%b)

[5 7 9]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4 2 2]
[4 2 2]
[1 2 3]
[1 2 3]


In [58]:
a = np.array([1,2,3])
a[0]=44
a

array([44,  2,  3])

In [60]:
b = np.array([4,5,6])
b[0:2]=[12,34]
b

array([12, 34,  6])

In [64]:
a = np.array([[1,23,4],[765,43,2]])
a[0][0]= 11
a[1][1:] = [44,56]
a

array([[ 11,  23,   4],
       [765,  44,  56]])

In [69]:
arange = np.arange(4)
print(arange)
print(type(arange))
print(arange.dtype)
print(arange.ndim)
print(len(arange))
print(arange.size)

[0 1 2 3]
<class 'numpy.ndarray'>
int64
1
4
4


In [78]:
ar = np.arange(12)
print(ar)
res_ar = ar.reshape((2,2,3))
print(res_ar)
print(res_ar.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3


In [110]:
a = np.array([[1,12,3],[4,56,6]],ndmin=10)
print(a)
print(a.shape)

[[[[[[[[[[ 1 12  3]
         [ 4 56  6]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 1, 2, 3)


In [95]:
arange = np.arange(70,dtype=float)
print(arange)
print(type(arange))
print(arange.dtype)
print(arange.ndim)
print(len(arange))
print(arange.size)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
<class 'numpy.ndarray'>
float64
1
70
70


In [99]:
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result
a = [1,2,3,4,5,[1,2,3,4,5,[9,8,7,6,5,[6,5,7,4,8]]]]
flatten(a)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 9, 8, 7, 6, 5, 6, 5, 7, 4, 8]

In [128]:
ls = np.linspace(10,11,num=18)
print(ls)
lin_arr = ls.reshape(3,3,2)
print(lin_arr)

[10.         10.05882353 10.11764706 10.17647059 10.23529412 10.29411765
 10.35294118 10.41176471 10.47058824 10.52941176 10.58823529 10.64705882
 10.70588235 10.76470588 10.82352941 10.88235294 10.94117647 11.        ]
[[[10.         10.05882353]
  [10.11764706 10.17647059]
  [10.23529412 10.29411765]]

 [[10.35294118 10.41176471]
  [10.47058824 10.52941176]
  [10.58823529 10.64705882]]

 [[10.70588235 10.76470588]
  [10.82352941 10.88235294]
  [10.94117647 11.        ]]]


In [135]:
lg = np.logspace(2,5,num=10)
lg

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [142]:
x = np.array([3,2,3,4,5,4,3,4])
mean = np.mean(x)
print(mean)
median = np.median(x)
print(median)
var = np.var(x)
print(var)
sd = np.std(x)
print(sd)

3.5
3.5
0.75
0.8660254037844386


In [149]:
x = np.array([34,14,51,62,25,48,34,72])
argmax = np.argmax(x)
argmin = np.argmin(x)
print(argmin,argmax)
min = np.min(x)
max = np.max(x)
print(min,max)
sum = np.sum(x)
print(sum)

1 7
14 72
340


In [174]:
copy_x = x.copy()
view = x.view()
print(copy_x)
print(view)

[ 34 400  51  62  25  48  34  72]
[ 34 400  51  62  25  48  34  72]


In [178]:
copy_x[1] = 400
print(x)

[ 34 400  51  62  25  48  34  72]


In [180]:
copy_x[1] = 40
print(copy_x)

[34 40 51 62 25 48 34 72]


In [181]:
print(x)
print(copy_x)
print(view)

[ 34 400  51  62  25  48  34  72]
[34 40 51 62 25 48 34 72]
[ 34 400  51  62  25  48  34  72]


In [197]:
x = np.array([[[1,2,3,4,54],[43,76,43,12,23]],[[12,5,35,98,12],[17,91,83,86,93]]])  
sort = np.sort(x,axis=None)
print(sort)

[ 1  2  3  4  5 12 12 12 17 23 35 43 43 54 76 83 86 91 93 98]


In [205]:
a1 = np.array([[1,21,3,43,54],[43,76,43,12,23]])
a2 = np.array([[12,5,35,98,12],[17,91,83,86,93]])

stack = np.stack((a1,a2),axis = 0)
print(stack)

[[[ 1 21  3 43 54]
  [43 76 43 12 23]]

 [[12  5 35 98 12]
  [17 91 83 86 93]]]


In [206]:
stack1 = np.stack((a1,a2),axis = 1)
print(stack1)

[[[ 1 21  3 43 54]
  [12  5 35 98 12]]

 [[43 76 43 12 23]
  [17 91 83 86 93]]]


In [210]:
x = np.array([[11,3],[3,3],[3,5]])
print(x)
x_t = x.T
print(x_t)

[[11  3]
 [ 3  3]
 [ 3  5]]
[[11  3  3]
 [ 3  3  5]]


In [212]:
rand = np.random.rand(3,2)
rand

array([[0.47522232, 0.80193732],
       [0.46656661, 0.66924503],
       [0.54953472, 0.75205849]])

In [214]:
rand = np.random.randn(3,2)
rand

array([[ 0.37301367,  0.40641683],
       [-0.31444925, -1.31049093],
       [-0.18515012,  0.08573674]])

In [220]:
rand = np.random.randint(2,10)
rand

8

In [221]:
rand = np.random.randint(2,10,size=100)
rand

array([8, 5, 4, 4, 3, 8, 7, 6, 5, 6, 9, 2, 8, 7, 3, 3, 2, 6, 5, 5, 9, 7,
       9, 4, 4, 2, 6, 6, 5, 4, 5, 3, 7, 7, 6, 2, 8, 3, 3, 5, 7, 2, 6, 4,
       6, 9, 3, 5, 2, 3, 6, 8, 2, 5, 7, 3, 7, 7, 6, 6, 8, 8, 8, 6, 4, 8,
       4, 8, 5, 6, 7, 8, 7, 8, 2, 9, 2, 2, 8, 7, 8, 3, 7, 2, 5, 7, 6, 9,
       5, 9, 5, 8, 9, 7, 6, 4, 7, 8, 3, 8], dtype=int32)

In [231]:
np.random.seed(0)
rand = np.random.randint(2,10)
rand


6